export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#584141",
        "on-secondary-fixed": "#221b00",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#ffb3b5",
        "inverse-primary": "#ffb3b5",
        "tertiary-fixed": "#e5e2e1",
        "surface-container": "#edeeef",
        "secondary-fixed": "#ffe16d",
        "surface-container-highest": "#e1e3e4",
        "primary-container": "#800020",
        tertiary: "#282727",
        "inverse-surface": "#2e3132",
        outline: "#8c7071",
        "on-secondary-container": "#6e5c00",
        "on-background": "#191c1d",
        "on-primary-container": "#ff828a",
        "surface-tint": "#af2b3e",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed": "#40000b",
        "on-primary-fixed-variant": "#8e0f28",
        "primary-fixed": "#ffdada",
        "on-tertiary-fixed": "#1c1b1b",
        error: "#ba1a1a",
        "surface-bright": "#f8f9fa",
        surface: "#f8f9fa",
        "secondary-container": "#fcd400",
        "on-tertiary-fixed-variant": "#474746",
        "on-secondary-fixed-variant": "#544600",
        "surface-variant": "#e1e3e4",
        "on-surface": "#191c1d",
        secondary: "#705d00",
        background: "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "surface-dim": "#d9dadb",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#c8c6c5",
        "tertiary-container": "#3e3d3d",
        "on-error-container": "#93000a",
        "surface-container-high": "#e7e8e9",
        "on-error": "#ffffff",
        primary: "#570013",
        "secondary-fixed-dim": "#e9c400",
        "on-tertiary-container": "#aaa8a7",
        "outline-variant": "#e0bfbf",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        mono: ["ui-monospace", "Consolas", "monospace"],
      },
      fontSize: {
        "headline-md": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.02em",
            fontWeight: "500",
          },
        ],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "display-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "container-padding": "32px",
        "stack-md": "24px",
        "stack-sm": "12px",
        gutter: "24px",
        "stack-lg": "48px",
        base: "8px",
      },
    },
  },
  plugins: [],
}
